import { ethers } from "hardhat";
import fs from "fs";
import path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with", deployer.address);

  // use ethers v6 deployment helpers
  const factory = await ethers.deployContract("EscrowFactory");
  await factory.waitForDeployment();

  const address = await factory.getAddress();
  const txHash = factory.deploymentTransaction?.hash ?? "";
  console.log("EscrowFactory deployed at:", address);
  console.log("Deployment tx:", txHash);

  // write addresses to frontend .env.local for immediate use
  const frontendEnvPath = path.resolve(__dirname, "../../frontend/.env.local");
  const lines = [] as string[];
  lines.push(`# Auto-generated by contracts/scripts/deploy.ts`);
  lines.push(`NEXT_PUBLIC_ESCROW_FACTORY_ADDRESS=${address}`);
  lines.push(`NEXT_PUBLIC_ESCROW_FACTORY_TX=${txHash}`);

  try {
    fs.writeFileSync(frontendEnvPath, lines.join("\n") + "\n");
    console.log("Wrote frontend env to", frontendEnvPath);
  } catch (e) {
    console.warn("Failed to write frontend env file:", (e as Error).message);
  }

  console.log("Done.");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
