import { ethers } from "hardhat";
import fs from "fs";
import path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with", deployer.address);

  // use ethers v6 deployment helpers
  const factory = await ethers.deployContract("EscrowFactory");
  await factory.waitForDeployment();

  const address = await factory.getAddress();
  let txHash = "";
  if (typeof factory.deploymentTransaction === "function") {
    const tx = factory.deploymentTransaction();
    txHash = tx && typeof tx.hash === "string" ? tx.hash : "";
  }
  console.log("EscrowFactory deployed at:", address);
  console.log("Deployment tx:", txHash);

  // append factory address to project root .env.local for frontend
  const rootEnvPath = path.resolve(__dirname, "../../.env.local");
  const lines = [] as string[];
  lines.push(`# Auto-generated by contracts/scripts/deploy.ts`);
  lines.push(`NEXT_PUBLIC_ESCROW_FACTORY_ADDRESS=${address}`);
  lines.push(`NEXT_PUBLIC_ESCROW_FACTORY_TX=${txHash}`);

  try {
    const existing = fs.existsSync(rootEnvPath) ? fs.readFileSync(rootEnvPath, "utf8") : "";
    const toAppend = lines.join("\n") + "\n";
    if (!existing.includes("NEXT_PUBLIC_ESCROW_FACTORY_ADDRESS=")) {
      fs.appendFileSync(rootEnvPath, toAppend);
      console.log("Appended factory address to", rootEnvPath);
    } else {
      console.log("NEXT_PUBLIC_ESCROW_FACTORY_ADDRESS already in .env.local — update manually to", address);
    }
  } catch (e) {
    console.warn("Could not write .env.local:", (e as Error).message);
  }

  console.log("Done.");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
