/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EscrowMilestoneFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "allEscrows" | "allEscrowsLength" | "createEscrowMilestone"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EscrowMilestoneCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "allEscrows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allEscrowsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrowMilestone",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "allEscrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allEscrowsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrowMilestone",
    data: BytesLike
  ): Result;
}

export namespace EscrowMilestoneCreatedEvent {
  export type InputTuple = [
    escrow: AddressLike,
    payer: AddressLike,
    payee: AddressLike
  ];
  export type OutputTuple = [escrow: string, payer: string, payee: string];
  export interface OutputObject {
    escrow: string;
    payer: string;
    payee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowMilestoneFactory extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowMilestoneFactory;
  waitForDeployment(): Promise<this>;

  interface: EscrowMilestoneFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allEscrows: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  allEscrowsLength: TypedContractMethod<[], [bigint], "view">;

  createEscrowMilestone: TypedContractMethod<
    [
      payer: AddressLike,
      payee: AddressLike,
      arbiter: AddressLike,
      token: AddressLike,
      totalAmount: BigNumberish,
      m1Amount: BigNumberish,
      m2Amount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allEscrows"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "allEscrowsLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createEscrowMilestone"
  ): TypedContractMethod<
    [
      payer: AddressLike,
      payee: AddressLike,
      arbiter: AddressLike,
      token: AddressLike,
      totalAmount: BigNumberish,
      m1Amount: BigNumberish,
      m2Amount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "EscrowMilestoneCreated"
  ): TypedContractEvent<
    EscrowMilestoneCreatedEvent.InputTuple,
    EscrowMilestoneCreatedEvent.OutputTuple,
    EscrowMilestoneCreatedEvent.OutputObject
  >;

  filters: {
    "EscrowMilestoneCreated(address,address,address)": TypedContractEvent<
      EscrowMilestoneCreatedEvent.InputTuple,
      EscrowMilestoneCreatedEvent.OutputTuple,
      EscrowMilestoneCreatedEvent.OutputObject
    >;
    EscrowMilestoneCreated: TypedContractEvent<
      EscrowMilestoneCreatedEvent.InputTuple,
      EscrowMilestoneCreatedEvent.OutputTuple,
      EscrowMilestoneCreatedEvent.OutputObject
    >;
  };
}
