/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EscrowFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "allEscrows" | "createEscrow" | "escrows"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EscrowCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "allEscrows",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrows",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "allEscrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowAddress: AddressLike,
    payer: AddressLike,
    payee: AddressLike,
    arbiter: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    escrowAddress: string,
    payer: string,
    payee: string,
    arbiter: string,
    amount: bigint
  ];
  export interface OutputObject {
    escrowAddress: string;
    payer: string;
    payee: string;
    arbiter: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowFactory extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowFactory;
  waitForDeployment(): Promise<this>;

  interface: EscrowFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allEscrows: TypedContractMethod<[], [string[]], "view">;

  createEscrow: TypedContractMethod<
    [
      payer: AddressLike,
      payee: AddressLike,
      arbiter: AddressLike,
      amount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  escrows: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allEscrows"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      payer: AddressLike,
      payee: AddressLike,
      arbiter: AddressLike,
      amount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;

  filters: {
    "EscrowCreated(address,address,address,address,uint256)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
  };
}
